openapi: 3.1.0
info:
  title: etonee123x's server
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local development server

security: []

paths:
  /upload:
    $ref: './paths/upload.yaml'

components:
  securitySchemes:
    bearerAuth:
      $ref: './components/securitySchemes/bearerAuth.yaml'