openapi: 3.1.0
info:
  title: etonee123x's server
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
security: []
paths:
  /upload:
    post:
      summary: Загрузить файл
      security:
        - bearerAuth: []
      operationId: uploadFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Файл успешно загружен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadResponse'
        '401':
          $ref: '#/components/responses/401'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UploadResponse:
      type: array
      items:
        type: string
        format: uri
      description: Массив ссылок на загруженные файлы
  responses:
    '401':
      description: Неавторизованный доступ
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: Unauthorized
