export enum HANDLER_NAME {
  GET_FOLDER_DATA = 'GET_FOLDER_DATA',
  FUNNY_ANIMALS = 'FUNNY_ANIMALS',
  HAPPY_NORMING = 'HAPPY_NORMING',
  POSTS = 'POSTS',
  UPLOAD = 'UPLOAD',
  CHECK_AUTH = 'CHECK_AUTH',
}
